---
# roles/desktop/tasks/main.yml
- name: Install core desktop packages and build dependencies
  apt:
    name:
      - i3-wm
      - polybar
      - rofi
      - lightdm
      - lightdm-gtk-greeter
      - lightdm-gtk-greeter-settings
      - picom
      - feh
      - xorg
      - alacritty
      - autoconf
      - automake
      - libtool
      - pkg-config
      - evince
      - mupdf
      - thunar
      - firefox
      - light-locker
      - xss-lock
      - pulseaudio
    state: present
    update_cache: yes

- name: Set Alacritty as default terminal
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/alacritty

- name: Copy LightDM configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: 'lightdm.conf', dest: '/etc/lightdm/lightdm.conf' }
    - { src: 'lightdm-gtk-greeter.conf', dest: '/etc/lightdm/lightdm-gtk-greeter.conf' }
  notify: Restart LightDM

- name: Set default graphical target
  systemd:
    name: graphical.target
    enabled: yes
    masked: no

- name: Enable LightDM service
  systemd:
    name: lightdm.service
    enabled: yes

- name: Add handler to restart lightdm
  meta: flush_handlers
