---
# roles/dotfiles/tasks/main.yml
- name: 競合する既存のデフォルトファイルを削除

  file:
    path: "/home/{{ user_name }}/{{ item }}"
    state: absent
  loop:
      - .bashrc
      - .bash_logout
      - .profile
      - .tmux.conf
      - .config/i3
      - .config/polybar
      - .config/rofi
      - .config/alacritty
      - .config/nvim

- name: .config ディレクトリの作成
  file:
    path: "/home/{{ user_name }}/.config"
    state: directory
    owner: "{{ user_name }}"
    mode: '0755'

- name: GNU Stowで設定ファイルを展開
  become: yes
  become_user: "{{ user_name }}"  # 一般ユーザー権限で実行してリンクの所有者を正しく保つ
  command: "stow -v -R -t /home/{{ user_name }}/ --dir={{ playbook_dir }}/dotfiles {{ item }}"
  loop:
    - bash
    - i3
    - polybar
    - rofi
    - tmux
    - alacritty
    - nvim
  register: stow_result
  changed_when: "'LINK' in stow_result.stdout"
