---
# roles/dotfiles/tasks/main.yml
- name: 競合する既存のデフォルトファイルを削除
  file:
    path: "/home/{{ user_name }}/{{ item }}"
    state: absent
  loop:
      - .bashrc
      - .bash_logout
      - .profile
      - .tmux.conf
      - .config/i3
      - .config/polybar
      - .config/rofi
      - .config/alacritty
      - .config/nvim

- name: .config ディレクトリの作成
  file:
    path: "/home/{{ user_name }}/.config"
    state: directory
    owner: "{{ user_name }}"
    mode: '0755'

- name: Install nvim-lspconfig as a native package
  become: yes
  become_user: "{{ user_name }}"
  git:
    repo: https://github.com/neovim/nvim-lspconfig
    dest: "/home/{{ user_name }}/.config/nvim/pack/nvim/start/nvim-lspconfig"
    depth: 1

- name: GNU Stowで設定ファイルを展開
  become: yes
  become_user: "{{ user_name }}"
  command: "stow -v -R -t /home/{{ user_name }}/ --dir={{ playbook_dir }}/dotfiles {{ item }}"
  loop:
    - bash
    - i3
    - polybar
    - rofi
    - tmux
    - alacritty
  register: stow_result
  changed_when: "'LINK' in stow_result.stdout"

- name: Change ownership of user dir recursively
  file:
    path: /home/n-komata
    owner: n-komata
    group: n-komata
    state: directory
    recurse: yes
