---
# roles/netplan/tasks/main.yml
- name: Copy netplan configuration
  copy:
    src: 00-installer-config.yaml
    dest: /etc/netplan/00-installer-config.yaml
    owner: root
    group: root
    mode: '0644'
  notify: Apply netplan

- name: Flush handlers to apply netplan config
  meta: flush_handlers

- block:
    - name: Netplan設定を適用 (Apply)
      command: netplan apply
  rescue:
    - name: Applyに失敗したため、Generateを試行
      command: netplan generate
      failed_when: false
