---
# roles/common/tasks/main.yml
- name: Install common packages
  apt:
    name:
      - git
      - tmux
      - fzf
      - ripgrep
      - neovim
      - curl
      - wget
      - build-essential
      - clang
      - unzip
      - stow
      - htop
      - evince
      - mupdf
      - thunar
      - network-manager
    state: present
    update_cache: yes
